apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  # Exposes the service using a NodePort for easy access
  ports:
    - port: 5002
      targetPort: 5002
  selector:
    app: fe
