apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-aws-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-aws-monitor
  template:
    metadata:
      labels:
        app: flask-aws-monitor
    spec:
      containers:
      - name: flask-aws-monitor
        image: yaniv8360/flask-aws-monitor:latest
        ports:
        - containerPort: 5001
