apiVersion: v1
kind: Service
metadata:
  name: flask-aws-monitor-service
spec:
  type: NodePort
  selector:
    app: flask-aws-monitor
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001
